// Auto-generated from TSV
export const initialProducts = [
    {
        "sku": "SM-F966BDBKCHO",
        "name": "Galaxy Z Fold7",
        "description": "Diseño ultra delgado 8.9mm, Cámara 200MP, Snapdragon 8 Elite y Galaxy AI.",
        "price": 19866,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_REVFsxTyaj9XMYmDK7Qf.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Azul Metálico",
        "colorHex": "#3c5b8a",
        "specs": [
            "512 GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-z-fold7"
    },
    {
        "sku": "SM-F766BDBJCHO",
        "name": "Galaxy Z Flip7",
        "description": "Cámara 50 MP, batería 4300 mAh, pantalla 2600 nits y FlexWindow.",
        "price": 10511,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_musoL4rQiqzg7KPlpEtb.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Azul Metálico",
        "colorHex": "#8d93a4",
        "specs": [
            "256 GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-z-flip7"
    },
    {
        "sku": "SM-F946BZEKBVO",
        "name": "Galaxy Z Fold 5",
        "description": "La potencia de una PC, ahora, en tu bolsillo.",
        "price": 16286,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_W9PG0iuCOkq34SbraYcn.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Crema",
        "colorHex": "#f8f4eb",
        "specs": [
            "256 GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-z-fold5"
    },
    {
        "sku": "SM-F946BZEKBVO",
        "name": "Galaxy Z Fold 5",
        "description": "La potencia de una PC, ahora, en tu bolsillo.",
        "price": 16690,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_W9PG0iuCOkq34SbraYcn.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Crema",
        "colorHex": "#f8f4eb",
        "specs": [
            "512 GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-z-fold5"
    },
    {
        "sku": "SM-S938BZTKBVO",
        "name": "Galaxy S25 Ultra",
        "description": "Cámara 200MP + 50MP, Titanio, Snapdragon 8 Elite y bat. 5000 mAh.",
        "price": 11839,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_qI9E4ZaOzVG1HFbrLPlf.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Gris",
        "colorHex": "#938e8a",
        "specs": [
            "512 GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-s25-ultra"
    },
    {
        "sku": "SM-S938BZTKBVO",
        "name": "Galaxy S25 Ultra",
        "description": "Cámara 200MP + 50MP, Titanio, Snapdragon 8 Elite y bat. 5000 mAh.",
        "price": 10915,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_qI9E4ZaOzVG1HFbrLPlf.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Gris",
        "colorHex": "#938e8a",
        "specs": [
            "256 GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-s25-ultra"
    },
    {
        "sku": "SM-S936BZSJBVO",
        "name": "Galaxy S25+",
        "description": "Pantalla QHD+ 6.7, batería 4900 mAh, Armor Aluminum y Galaxy AI.",
        "price": 9644,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_QFnUNhV2vgt5lCTS1jEr.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Gris",
        "colorHex": "#747477",
        "specs": [
            "256 GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-s25"
    },
    {
        "sku": "SM-S931BLBKBVO",
        "name": "Galaxy S25",
        "description": "Pantalla FHD+ 6.2, batería 4000 mAh, 12GB RAM y diseño compacto.",
        "price": 8258,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_a8UgdYvuW1GTco4Ei0jt.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Celeste",
        "colorHex": "#bac3d3",
        "specs": [
            "256 GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-s25"
    },
    {
        "sku": "SM-A566EZKCBVO",
        "name": "Galaxy-A56 5G",
        "description": "Pantalla Super AMOLED, cuerpo de 7.4mm, Super HDR y marco de aluminio.",
        "price": 4216,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_gRcO0dDIHaKpQkyrB1Ce.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Grafito",
        "colorHex": "#53565a",
        "specs": [
            "256GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a56-5g-awesome-graphite-256gb-sm-a566ezkcbvo"
    },
    {
        "sku": "SM-S731BDBKBVO",
        "name": "Galaxy-A56 5G",
        "description": "Pantalla Super AMOLED, cuerpo de 7.4mm, Super HDR y marco de aluminio.",
        "price": 3962,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_gRcO0dDIHaKpQkyrB1Ce.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Grafito",
        "colorHex": "#53565a",
        "specs": [
            "256GB",
            "RAM 8GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a56-5g-awesome-graphite-256gb-sm-a566ezkcbvo"
    },
    {
        "sku": "SM-S731BDBKBVO",
        "name": "Galaxy-A55 5G",
        "description": "Pantalla Super AMOLED, cuerpo de 7.4mm, Super HDR y marco de aluminio.",
        "price": 4158,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_PJyW02YS6HQF8Mmhk4TK.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [
            "256GB",
            "RAM 8GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a55-5g"
    },
    {
        "sku": "SM-A366ELGGBVO",
        "name": "Galaxy-A36 5G",
        "description": "Pantalla 6.7 FHD+ 120Hz (1200 nits), Knox Vault y diseño minimalista.",
        "price": 3361,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_6vXGmDeB8ETVyJrIqut3.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Verde claro",
        "colorHex": "#dfefdb",
        "specs": [
            "256GB",
            "RAM 8GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a36-5g-awesome-black-256gb-sm-a366ezkgbvo"
    },
    {
        "sku": "SM-A356EZKGBVO",
        "name": "Galaxy-A35",
        "description": "Conoce la brillante pantalla FHD+ Super AMOLED Infinity-O display de 6.6 pulgadas",
        "price": 3581,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_b2BqZAs5agKoxGz7EeOD.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Negro",
        "colorHex": "#2d2926",
        "specs": [
            "256GB",
            "RAM 8GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a35-5g"
    },
    {
        "sku": "SM-A266MZKDBVO",
        "name": "Galaxy-A26 5G",
        "description": "Pantalla 6.7 Super AMOLED, IP67, Batería 5000mAh y diseño Key Island.",
        "price": 2680,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_CzrmjgMaNsDTUn1v6bcu.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Negro",
        "colorHex": "#2d2926",
        "specs": [
            "256GB",
            "RAM 6GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a26-5g-black-256gb-sm-a266mzkhbvo"
    },
    {
        "sku": "SM-A266MZKDBVO",
        "name": "Galaxy-A26 5G",
        "description": "Pantalla 6.7 Super AMOLED, IP67, Batería 5000mAh y diseño Key Island.",
        "price": 2506,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_CzrmjgMaNsDTUn1v6bcu.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Negro",
        "colorHex": "#2d2926",
        "specs": [
            "128 GB",
            "RAM 6GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a26-5g-black-256gb-sm-a266mzkhbvo"
    },
    {
        "sku": "SM-A256EZKHBVO",
        "name": "Galaxy-A25",
        "description": "Rápido, espacioso y poderoso. Todo lo que necesitas para hacer más",
        "price": 2287,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/original/product-family-item-image-image_2fFTNI7g9YcGVydKMDP3.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Azul Oscuro",
        "colorHex": "#3f4251",
        "specs": [
            "128 GB",
            "RAM 6GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a25-5g-blue-black-256gb-sm-a256ezkhbvo"
    },
    {
        "sku": "SM-A175FZKGBVO",
        "name": "Galaxy-A17",
        "description": "Diseño moderno, cámara principal 50MP y batería de 5000mAh para todo el día.",
        "price": 2333,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_plKXQsWNif5GCyvtuD8S.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Negro",
        "colorHex": "#404145",
        "specs": [
            "256GB",
            "RAM 8GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a17-black-128gb-sm-a175fzkgbvo"
    },
    {
        "sku": "SM-A175FZKGBVO",
        "name": "Galaxy-A17",
        "description": "Diseño moderno, cámara principal 50MP y batería de 5000mAh para todo el día.",
        "price": 1906,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_plKXQsWNif5GCyvtuD8S.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Negro",
        "colorHex": "#404145",
        "specs": [
            "128 GB",
            "RAM 6GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a17-black-128gb-sm-a175fzkgbvo"
    },
    {
        "sku": "SM-A165MLGIBVO",
        "name": "Galaxy-A16",
        "description": "Pantalla 6.7 FHD+ sAMOLED, 6 actualizaciones de seguridad y diseño ultra delgado.",
        "price": 2056,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_XdSCZYtRWLMcFa3QbyPH.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Light Green",
        "colorHex": "#c0cdc4",
        "specs": [
            "256 GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a16-black-128gb-sm-a165mzkgbvo"
    },
    {
        "sku": "SM-A165MLGIBVO",
        "name": "Galaxy-A16",
        "description": "Pantalla 6.7 FHD+ sAMOLED, 6 actualizaciones de seguridad y diseño ultra delgado.",
        "price": 1813,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_XdSCZYtRWLMcFa3QbyPH.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Light Green",
        "colorHex": "#c0cdc4",
        "specs": [
            "128 GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a16-black-128gb-sm-a165mzkgbvo"
    },
    {
        "sku": "SM-A065MZKDBVO",
        "name": "Galaxy-A06",
        "description": "Pantalla 6.7, Cámara 50MP, Carga rápida 25W y lector de huella lateral.",
        "price": 1259,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_q2igFyLm8vBEX07xUAGu.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Negro",
        "colorHex": "#484d57",
        "specs": [
            "128 GB",
            "RAM 6GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a06"
    },
    {
        "sku": "SM-A065MZKDBVO",
        "name": "Galaxy-A06",
        "description": "Pantalla 6.7, Cámara 50MP, Carga rápida 25W y lector de huella lateral.",
        "price": 1155,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_q2igFyLm8vBEX07xUAGu.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Negro",
        "colorHex": "#484d57",
        "specs": [
            "64 GB",
            "RAM 4GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a06"
    },
    {
        "sku": "SM-A057MLVGBVO",
        "name": "Galaxy-A05s",
        "description": "El Galaxy A05s: potencia Snapdragon, cámara 50MP y batería 5000 mAh. ¡Estilo y rendimiento accesibles!",
        "price": 1398,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_HWoSn1O3YCMgQsTl9wib.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Violeta",
        "colorHex": "#b4b5df",
        "specs": [
            "128GB",
            "RAM 4GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a05s-light-violet-128gb-sm-a057mlvgltl"
    },
    {
        "sku": "SM-A055MZSABVO",
        "name": "Galaxy-A05",
        "description": "Pantalla HD+ inmersiva, cámara 50MP y batería 5000 mAh. ¡Esencial, potente y accesible!",
        "price": 1097,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_H4yrzjgaoxPnts8SOGup.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Plata",
        "colorHex": "#cbc6c4",
        "specs": [
            "128GB",
            "RAM 4GB"
        ],
        "link": "https://samsung.com.bo/smartphones/galaxy-a/galaxy-a05-silver-64gb-sm-a055mzsaltm"
    },
    {
        "sku": "SM-A055MZSABVO",
        "name": "Galaxy-A05",
        "description": "Pantalla HD+ inmersiva, cámara 50MP y batería 5000 mAh. ¡Esencial, potente y accesible!",
        "price": 959,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_H4yrzjgaoxPnts8SOGup.png",
        "mainCategory": "Smartphones",
        "category": "Smartphones",
        "color": "Plata",
        "colorHex": "#cbc6c4",
        "specs": [
            "64GB",
            "RAM 4GB"
        ],
        "link": "https://samsung.com.bo/seriegalaxya"
    },
    {
        "sku": "SM-X920NZADBVO",
        "name": "Galaxy Tab S10 Ultra Wi-Fi + Keyboard Cover + S Pen",
        "description": "Pantalla 14.6 Dynamic AMOLED 2x, cuerpo de 718g y resistencia IP68.",
        "price": 13283,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_ak0VR2Sfu7AGJmtyDW81.png",
        "mainCategory": "Tablets",
        "category": "Tablets",
        "color": "Gray",
        "colorHex": "#606e81",
        "specs": [
            "256GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/tablets/galaxy-tab-s/galaxy-tab-s10-ultra-gray-256gb-sm-x920nzadbvo"
    },
    {
        "sku": "SM-X716BZAEBVO",
        "name": "Galaxy Tab S9 5G + S Pen",
        "description": "Pantalla Dynamic AMOLED 2X, Vision Booster y procesador Snapdragon 8 Gen 2.",
        "price": 11319,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_a47qwBkQmGSDLxrnHbl2.png",
        "mainCategory": "Tablets",
        "category": "Tablets",
        "color": "Graphite",
        "colorHex": "#545356",
        "specs": [
            "256GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/tablets/galaxy-tab-s/galaxy-tab-s9-graphite-256gb-sm-x716bzaebvo"
    },
    {
        "sku": "SM-X900NZADBVO",
        "name": "Galaxy Tab S8 Ultra Wi-Fi + Keyboard Cover + S Pen",
        "description": "Pantalla 14.6 Super AMOLED, doble cámara frontal 12MP y batería 11200mAh.",
        "price": 9702,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/original/product-family-item-image-image_r9kBXbZ7EHPeI415nwMF.png",
        "mainCategory": "Tablets",
        "category": "Tablets",
        "color": "Graphite",
        "colorHex": "#494d53",
        "specs": [
            "256GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/tablets/galaxy-tab-s8-ultra"
    },
    {
        "sku": "SM-X906BZADBVO",
        "name": "Galaxy Tab S8 Ultra 5G + Keyboard Cover + S Pen",
        "description": "Pantalla masiva 14.6 sAMOLED, conectividad 5G, doble cámara frontal y batería 11200mAh.",
        "price": 10857,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_Ym12EgZftRjDsOCp9o6i.png",
        "mainCategory": "Tablets",
        "category": "Tablets",
        "color": "Graphite",
        "colorHex": "#494d53",
        "specs": [
            "256GB",
            "RAM 12GB"
        ],
        "link": "https://samsung.com.bo/tablets/galaxy-tab-s/galaxy-tab-s8-ultra-5g-graphite-256gb-sm-x906bzadbvo"
    },
    {
        "sku": "SM-X620NZSABVO",
        "name": "Galaxy Tab S10 FE+ Wi-Fi + Cover + S Pen",
        "description": "Pantalla masiva de 13.1, resistencia al agua IP68 y S Pen Creator incluido.",
        "price": 7854,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_2k8sHTFRoQNY0nq694dh.png",
        "mainCategory": "Tablets",
        "category": "Tablets",
        "color": "Silver",
        "colorHex": "#c0c0c0",
        "specs": [
            "128GB",
            "RAM 8GB"
        ],
        "link": "https://samsung.com.bo/tablets/galaxy-tab-s/galaxy-tab-s10-ultra-gray-256gb-sm-x920nzadbvo"
    },
    {
        "sku": "SM-X406BZADBVO",
        "name": "Galaxy Tab S10 Lite 5G + Cover + S Pen",
        "description": "Pantalla con Low Blue Light, soporte MicroSD hasta 2TB y diseño ligero.",
        "price": 4851,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_WxlKTwnyCDmuqzFNbOEc.png",
        "mainCategory": "Tablets",
        "category": "Tablets",
        "color": "Gris",
        "colorHex": "#75787b",
        "specs": [
            "128GB",
            "RAM 6GB"
        ],
        "link": "https://samsung.com.bo/tablets/galaxy-tab-s/galaxy-tab-s10-lite-gray-128gb-sm-x406bzadbvo/"
    },
    {
        "sku": "SM-P615NZAUBVO",
        "name": "Galaxy Tab S6 Lite + S Pen",
        "description": "Diseño metálico 10.4, S Pen magnético, One UI y sonido AKG.",
        "price": 3869,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_cK7fN9BtLdoA2XSxZHq4.png",
        "mainCategory": "Tablets",
        "category": "Tablets",
        "color": "Gray",
        "colorHex": "#75787b",
        "specs": [
            "64GB",
            "RAM 4GB"
        ],
        "link": "https://samsung.com.bo/tablets/galaxy-tab-s/galaxy-tab-s6-lite-10-4-inch-gray-64gb-wi-fi-sm-p625nzaabvo"
    },
    {
        "sku": "SM-X216BZAABVO",
        "name": "Galaxy Tab A9+ 5G",
        "description": "Gran pantalla envolvente, cámara versátil y un diseño elegante para tu entretenimiento diario.",
        "price": 2714,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_GVSg1FfkhnQMwBlorKJP.png",
        "mainCategory": "Tablets",
        "category": "Tablets",
        "color": "Gray",
        "colorHex": "#2a3244",
        "specs": [
            "64GB",
            "RAM 4GB"
        ],
        "link": "https://samsung.com.bo/tablets/galaxy-tab-a/galaxy-tab-a9-plus-5g-gray-64gb-sm-x216bzaabvo"
    },
    {
        "sku": "SM-X115NZAEL12",
        "name": "Galaxy Tab A9",
        "description": "Sumérgete en la Galaxy Tab A9: pantalla compacta, sonido Dolby Atmos, rendimiento fluido y diseño metálico portátil.",
        "price": 1386,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_wOeUva34LZ5by708tVNP.png",
        "mainCategory": "Tablets",
        "category": "Tablets",
        "color": "Gray",
        "colorHex": "#2a3244",
        "specs": [
            "128GB",
            "RAM 8GB"
        ],
        "link": "https://samsung.com.bo/tablets/galaxy-tab-a/galaxy-tab-a9-wifi-mystic-navy-128gb-sm-x115nzael12"
    },
    {
        "sku": "SM-L330NZSALTA",
        "name": "Galaxy Watch8 44mm",
        "description": "Diseño ultra delgado, procesador de 3nm, sensor BioActive avanzado y GPS de doble frecuencia.",
        "price": 3696,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_Cni83qS4IomVYGdFb7P6.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Silver",
        "colorHex": "#c7c8ca",
        "specs": [],
        "link": "https://samsung.com.bo/galaxy-watch/galaxy-watch8-44mm-silver-bluetooth-sm-l330nzsalta"
    },
    {
        "sku": "SM-L320NZSALTA",
        "name": "Galaxy Watch8 40mm",
        "description": "Diseño acolchado icónico, monitor de sueño con IA y pantalla más brillante.",
        "price": 3407,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_9uv4ihWUsJkdFA3zZeg2.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Silver",
        "colorHex": "#c7c8ca",
        "specs": [],
        "link": "https://samsung.com.bo/galaxy-watch/galaxy-watch8-40mm-graphite-bluetooth-sm-l320ndaalta"
    },
    {
        "sku": "SM-L310NZGALTA",
        "name": "Galaxy Watch7 44mm",
        "description": "Procesador de 3nm, GPS de doble frecuencia y monitoreo de salud con Galaxy AI.",
        "price": 3234,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_I42cMghpFfwX8o0Qb1JV.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Green",
        "colorHex": "#6e6d63",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch7-44mm-green-bluetooth-sm-l310nzgalta"
    },
    {
        "sku": "SM-L300NZGALTA",
        "name": "Galaxy Watch7 40mm",
        "description": "Compacto y potente, control de gestos doble pellizco y batería de larga duración.",
        "price": 3003,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_PHQG26DIV3dK5LlOoj1u.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Verde",
        "colorHex": "#6e6d63",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch7-40mm-green-bluetooth-sm-l300nzgalta"
    },
    {
        "sku": "SM-R960NZSALTA",
        "name": "Galaxy Watch6 Classic 47mm",
        "description": "Bisel giratorio físico, pantalla de cristal de zafiro y diseño clásico de gran formato.",
        "price": 4216,
        "salePrice": 0,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/py/2307/gallery/py-galaxy-watch6-classic-r965-sm-r960nzsalta-537413468?$Q90_1920_1280_F_PNG$",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Silver",
        "colorHex": "#c7c8ca",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch6-40mm-graphite-bluetooth-sm-r930nzkalta"
    },
    {
        "sku": "SM-R950NZKAPHE",
        "name": "Galaxy Watch6 Classic 43mm",
        "description": "Elegancia atemporal con bisel giratorio, seguimiento de salud 24/7 y diseño refinado.",
        "price": 3869,
        "salePrice": 0,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/es/2307/gallery/es-galaxy-watch6-classic-r955-sm-r950nzsaphe-537448677?$Q90_684_547_JPG$",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Silver",
        "colorHex": "#c7c8ca",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch6-40mm-graphite-bluetooth-sm-r930nzkalta"
    },
    {
        "sku": "SM-R940NZSALTA",
        "name": "Galaxy Watch6 44mm",
        "description": "Pantalla más amplia y bisel reducido para maximizar tu visión y bienestar.",
        "price": 3061,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_U5bBtS1grukPQy8FDwqH.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Silver",
        "colorHex": "#c7c8ca",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch6-40mm-graphite-bluetooth-sm-r930nzkalta"
    },
    {
        "sku": "SM-R930NZEALTA",
        "name": "Galaxy Watch6 40mm",
        "description": "Pantalla más amplia y bisel reducido para maximizar tu visión y bienestar.",
        "price": 2657,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_3eaB1ZH8XMfgArRizST6.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Gold",
        "colorHex": "#f0eae0",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch6-40mm-graphite-bluetooth-sm-r930nzkalta"
    },
    {
        "sku": "SM-R920NZKALTA",
        "name": "Galaxy Watch5 Pro",
        "description": "Batería de larga duración y cuerpo de titanio diseñado para la aventura extrema.",
        "price": 2657,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_OQZW4xiHv7MwbqRgefo1.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Negro",
        "colorHex": "#404145",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch5-pro-black-titanium-bluetooth-sm-r920nzkalta"
    },
    {
        "sku": "SM-R910NZAALTA",
        "name": "Galaxy Watch5 44mm",
        "description": "Tecnología de sensor bioactivo para un análisis integral de sueño y salud diaria.",
        "price": 2426,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_U439qx2GkFwOBPhb8IQo.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Graphite",
        "colorHex": "#4a4a4d",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch5-44mm-graphite-bluetooth-sm-r910nzaalta"
    },
    {
        "sku": "SM-R900NZSALTA",
        "name": "Galaxy Watch5 40mm",
        "description": "Tecnología de sensor bioactivo para un análisis integral de sueño y salud diaria.",
        "price": 1964,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_P1oG408CDeJMg92NFqIu.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Plateado",
        "colorHex": "#c7c8c9",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch5-40mm-silver-bluetooth-sm-r900nzsalta"
    },
    {
        "sku": "SM-R860NZDALTA",
        "name": "Galaxy Watch4 40mm",
        "description": "Diseño icónico y compacto con medición de composición corporal para tu vida fitness.",
        "price": 1733,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_Fw8gsRPMqfK3Tj0SzeB5.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Oro Rosado",
        "colorHex": "#ffc0cb",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch4-pink-gold-bluetooth-sm-r860nzdalta"
    },
    {
        "sku": "SM-R861NZSALTA",
        "name": "Galaxy Watch FE",
        "description": "Las funciones esenciales de bienestar y conectividad Galaxy a tu alcance cada día.",
        "price": 2137,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_no1kELFZ2z4lgwKMY7pe.png",
        "mainCategory": "Smartwatches",
        "category": "Smartwatches",
        "color": "Silver",
        "colorHex": "#c0c0c0",
        "specs": [],
        "link": "https://samsung.com.bo/watches/galaxy-watch/galaxy-watch-fe-40mm-silver-bluetooth-sm-r861nzsalta"
    },
    {
        "sku": "UN50DU8000GXZS",
        "name": "50\" Crystal UHD 4K DU8000 Smart TV (2024)",
        "description": "Sumergete en mil millones de tonos de color para una imagen clara y llena de detalle",
        "price": 3629,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_KDOShpEvQ4lBfnFIo5xq.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/uhd-4k-tv/du8000-50-inch-crystal-uhd-4k-tizen-os-smart-tv-un50du8000gxzs"
    },
    {
        "sku": "UN55DU8000GXZS",
        "name": "55\" Crystal UHD 4K DU8000 Smart TV (2024)",
        "description": "Sumergete en mil millones de tonos de color para una imagen clara y llena de detalle",
        "price": 4366,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_ImkfcVMrtUGxSCTOywjK.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/uhd-4k-tv/du8000-55-inch-crystal-uhd-4k-tizen-os-smart-tv-un55du8000gxzs"
    },
    {
        "sku": "UN65U8000FGXZS",
        "name": "65\" Crystal UHD 4K U8000F Smart TV",
        "description": "Sumergete en mil millones de tonos de color para una imagen clara y llena de detalle",
        "price": 7040,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_QpGz43vgsMNwIVbXqoLF.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/uhd-4k-tv/u8000f-65-inch-crystal-uhd-4k-smart-tv-un65u800fgxzs"
    },
    {
        "sku": "QN65LS03DAGXZS",
        "name": "65 The Frame QLED 4K Smart TV (2024)",
        "description": "Televisor o cuadro de arte tu eliges; disfruta de tu pantalla anti-reflejo con matte display",
        "price": 11000,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_m8TwsQ7c1RFViLxje3vO.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/lifestyle-tvs/the-frame/ls03d-65-inch-black-qn65ls03dagxzs"
    },
    {
        "sku": "UN98DU9000GXZS",
        "name": "98 Crystal UHD 4K DU9000 Smart TV (2024)",
        "description": "Sumergete en mil millones de tonos de color para una imagen clara y llena de detalle",
        "price": 39078,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_Uh2PdWwkltZ9JBaoFK1u.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/uhd-4k-tv/du9000-98-inch-crystal-uhd-4k-tizen-os-smart-tv-un98du9000gxzs"
    },
    {
        "sku": "QN85Q70AAGXZS",
        "name": "85 QLED 4K Q70A Smart TV (2021)",
        "description": "Hasta 100% de volumen de color con brillo que resalta incluso de dia",
        "price": 16499,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_Je9G8vLxcWoRBu6Qj3CO.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/qled"
    },
    {
        "sku": "QN50Q7FAAGXZS",
        "name": "50 QLED Q7FA 4K Vision Al Smart TV (2025)",
        "description": "Hasta 100% de volumen de color con brillo que resalta incluso de dia",
        "price": 4488,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_5GWkeRcMV4v2oZByOLHb.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/qled-tv/q7f-50-inch-qled-4k-smart-tv-qn50q7faagxzs"
    },
    {
        "sku": "QN55Q6FAAGXZS",
        "name": "55 QLED Q7FA 4K Vision Al Smart TV (2025)",
        "description": "Hasta 100% de volumen de color con brillo que resalta incluso de dia",
        "price": 5676,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_J19o5VW0lxjv8ZAPXb3q.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/qled-tv/q7f-55-inch-qled-4k-smart-tv-qn55q7faagxzs"
    },
    {
        "sku": "QN65Q6FAAGXZS",
        "name": "65 QLED Q7FA 4K Vision Al Smart TV (2025)",
        "description": "Hasta 100% de volumen de color con brillo que resalta incluso de dia",
        "price": 7920,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_y3SazKNiqZL2GgWMDAB1.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/qled-tv/q7f-65-inch-qled-4k-smart-tv-qn65q7faagxzs"
    },
    {
        "sku": "QN75Q6FAAGXZS",
        "name": "75 QLED Q7FA 4K Vision Al Smart TV (2025)",
        "description": "Hasta 100% de volumen de color con brillo que resalta incluso de dia",
        "price": 12540,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_Fh0QtAWP2TrMlOyfKH3i.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/qled-tv/q7f-75-inch-qled-4k-smart-tv-qn75q7faagxzs"
    },
    {
        "sku": "QN85Q7FAAGXZS",
        "name": "Televisor Smart 85 QLED 4K Q7F (2025)",
        "description": "Hasta 100% de volumen de color con brillo que resalta incluso de dia",
        "price": 18480,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_y3SazKNiqZL2GgWMDAB1.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/qled-tv/q7f-85-inch-qled-4k-smart-tv-qn85q7faagxzs"
    },
    {
        "sku": "QN65S90FAEXZS",
        "name": "65 OLED 4K S85F Smart TV (2025)",
        "description": "Tecnología OLED con negros profundos, Pantone Validated y diseño LaserSlim.",
        "price": 18480,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_aBiCzY5V7jtclEme09N6.png",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/tvs/oled-tv/s90f-65-inch-oled-4k-smart-tv-qn65s90faexzs"
    },
    {
        "sku": "QN77S85FAEXZS",
        "name": "77\" OLED S85F 4K Vision AI Smart TV (2025)",
        "description": "Tecnología OLED con negros profundos, Pantone Validated y diseño LaserSlim.",
        "price": 29040,
        "salePrice": 0,
        "image": "https://images.samsung.com/is/image/samsung/p6pim/cl/qn77s85faexzs/gallery/cl-oled-s85f-qn77s85faexzs-545961780?$Q90_1368_1094_F_JPG$",
        "mainCategory": "Televisores",
        "category": "Televisores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://shop.samsung.com.bo/tvs/oled-tv/s90f-77-inch-oled-4k-smart-tv-qn77s90faexzs"
    },
    {
        "sku": "HW-Q800F/ZS",
        "name": "Q-Series Soundbar HW-Q800F 5.1.2 Subwoofer (2025)",
        "description": "Altavoces laterales para una inmersión acústica total.",
        "price": 4488,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_zLvAhkBV4oGt1xSOlbHY.png",
        "mainCategory": "Equipos de Audio",
        "category": "Equipos de Audio",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/audio-devices/soundbar/q800f-black-hw-q800f-zs"
    },
    {
        "sku": "HW-QS700F/ZS",
        "name": "Q-Series Soundbar HW-QS700F 3.1.2 Subwoofer",
        "description": "Excelente calidad de sonido en cualquier configuración. El diseño inteligente se ve bien tanto en su posición vertical como horizontal.",
        "price": 5280,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_UC9FgdPpQ1ntN5zfOkho.png",
        "mainCategory": "Equipos de Audio",
        "category": "Equipos de Audio",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/audio-devices/soundbar/qs700f-black-hw-qs700f-zs"
    },
    {
        "sku": "WA13T5260BW/ZS",
        "name": "Lavadora de carga superior con dosificador Magic Dispenser",
        "description": "Tecnología Wobble anti-enredos, Motor DIT y diseño moderno.",
        "price": 4043,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_JT9UujprqxAOCeYIymol.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Blanco",
        "colorHex": "#ffffff",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/top-load-13kg-white-wa13t5260bw-zs"
    },
    {
        "sku": "WA13T5260BY/ZS",
        "name": "Lavadora de carga superior con dosificador Magic Dispenser",
        "description": "Tecnología Wobble anti-enredos, Motor DIT y diseño moderno.",
        "price": 4274,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_EkvnsOYoGfTQXcBILRhS.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Gris",
        "colorHex": "#777777",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/top-load-13kg-gray-wa13t5260by-zs"
    },
    {
        "sku": "WA13CG5441BWZS",
        "name": "Lavadora Carga Superior 13Kg c/ Wobble",
        "description": "Tecnología Wobble, Lavado Intenso y ahorro de energía.",
        "price": 4043,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_su85rYTHDQ31oNcFkqKC.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "White",
        "colorHex": "#ffffff",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/wa5000c-top-load-ecobubble-digital-inverter-technology-super-speed-13kg-white-wa13cg5441bwzs"
    },
    {
        "sku": "WA13CG5441BDZS",
        "name": "Lavadora Carga Superior 13Kg c/ Wobble",
        "description": "Tecnología Wobble, Lavado Intenso y ahorro de energía.",
        "price": 4274,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_Uo1X7Wfh25ta9TM0Oszx.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Gray",
        "colorHex": "#808080",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/wa5000c-top-load-ecobubble-digital-inverter-technology-super-speed-13kg-white-wa13cg5441bwzs"
    },
    {
        "sku": "WA15T5260BY/ZS",
        "name": "Lavadora Carga Superior 15Kg c/ Wobble",
        "description": "Capacidad 15Kg, Pulsador Wobble y 20 años de garantía en motor.",
        "price": 4736,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_TMWkD26xISQhd3vbeO7F.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Gris",
        "colorHex": "#777777",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/top-load-15kg-white-wa15t5260bw-zs"
    },
    {
        "sku": "WA15T5260BW/ZS",
        "name": "Lavadora Carga Superior 15Kg c/ Wobble",
        "description": "Capacidad 15Kg, Pulsador Wobble y 20 años de garantía en motor.",
        "price": 4505,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_zn79NiAjgpXSa02KERrW.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "White",
        "colorHex": "#ffffff",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/top-load-15kg-white-wa15t5260bw-zs"
    },
    {
        "sku": "WA19CG6441BDZS",
        "name": "Lavadora Carga Superior 19Kg c/ Eco Bubble",
        "description": "EcoBubble con Dual Storm, Speed Spray (Lavado 31min) y SmartThings.",
        "price": 6468,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_gkcsF4KAm19xdWathDey.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Gris",
        "colorHex": "#808080",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/wa6000c-top-load-ecobubble-digital-inverter-technology-super-speed-19kg-gray-wa19cg6441bdzs"
    },
    {
        "sku": "WA19CG6745BVZS",
        "name": "Lavadora Carga Superior 19Kg c/ Eco Bubble",
        "description": "EcoBubble con Dual Storm, Speed Spray (Lavado 31min) y SmartThings.",
        "price": 6699,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_4ALNrH3PaGJvw50B6Ykz.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/wa6000c-top-load-ecobubble-digital-inverter-technology-super-speed-19kg-gray-wa19cg6441bdzs"
    },
    {
        "sku": "WA19T6260BY/BO",
        "name": "Lavadora Carga Superior 19Kg c/ Wobble",
        "description": "Lavadora de carga superior con dosificador Magic Dispenser, lavado intenso y suavizante potente",
        "price": 6353,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_2EcOMLa84g03ws7PhJld.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Gris",
        "colorHex": "#808080",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/top-load-19kg-black-caviar-wa19t6260bv-bo"
    },
    {
        "sku": "WA22A8370GV/BO",
        "name": "Lavadora Carga Superior 22Kg c/ Bubble Storm",
        "description": "Heavy Duty+, BubbleStorm para lavado rápido y gran capacidad 22kg.",
        "price": 9818,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_Efvjbaz4T2p1qsVgYC8N.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/ww8800a-22kg-black-wa22a8370gv-bo"
    },
    {
        "sku": "WW10TA040CX/BO",
        "name": "Lavadora Carga Frontal 10.5Kg c/ Eco Bubble",
        "description": "Lavado con IA (AI Control), EcoBubble y Dispensador Automático.",
        "price": 6468,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_krILGRP5XyFmbe0hjVWJ.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Gris",
        "colorHex": "#808080",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/ww5000t-front-loading-hygiene-steam-dit-10-5kg-white-ww10ta040ce-bo"
    },
    {
        "sku": "WW10TA040CE/BO",
        "name": "Lavadora Carga Frontal 10.5Kg c/ Eco Bubble",
        "description": "Lavado con IA (AI Control), EcoBubble y Dispensador Automático.",
        "price": 6122,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_3uKoTkXGRYyDQgqJ6Sbz.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Blanco",
        "colorHex": "#ffffff",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/ww5000t-front-loading-hygiene-steam-dit-10-5kg-white-ww10ta040ce-bo"
    },
    {
        "sku": "WA90H4400SW",
        "name": "Lavadora Carga Superior 9Kg c/ Wobble",
        "description": "Modelo compacto, Wobble Technology y secado de aire turbo.",
        "price": 3119,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_dxZmHuRywXpgqTN0LfMe.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Blanco",
        "colorHex": "#ffffff",
        "specs": [],
        "link": "https://samsung.com.bo/washers/wa90h4400sw"
    },
    {
        "sku": "WA90CG4240BYZS",
        "name": "Lavadora de carga superior 9Kg con tecnología Digital Inverter",
        "description": "Disfruta de un rendimiento duradero con la Tecnología Digital Inverter",
        "price": 3119,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_te30L7Zgu4Da1fjSKrw6.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Gray",
        "colorHex": "#808080",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/wa4000c-top-load-ecobubble-digital-inverter-technology-super-speed-9kg-light-gray-wa90cg4240byzs"
    },
    {
        "sku": "WW85T3040BW/BO",
        "name": "Lavadora Carga Frontal 8.5Kg c/ Lavado Rápido",
        "description": "Motor Digital Inverter, Lavado Rápido 18min y Limpieza de Tambor.",
        "price": 4736,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_DOBy17IHf4CUA8VwtipF.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Blanco",
        "colorHex": "#ffffff",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/front-load-8-5kg-white-ww85t3040bw-bo"
    },
    {
        "sku": "WA80CG4240BWZS",
        "name": "Lavadora de carga superior 8Kg con tecnología Digital Inverter",
        "description": "Disfruta de un rendimiento duradero con la Tecnología Digital Inverter",
        "price": 2888,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_xiIa67VGcX5KmtYyA8fJ.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Blanco",
        "colorHex": "#ffffff",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washing-machines/wa4000c-top-load-ecobubble-digital-inverter-technology-super-speed-8kg-white-wa80cg4240bwzs"
    },
    {
        "sku": "WA80H4200SW",
        "name": "Lavadora Carga Superior 8Kg c/ Wobble",
        "description": "Diseño duradero, tina de diamantes y panel de control trasero.",
        "price": 2888,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_CFsI3gma41uDhQrA7LS8.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Blanco",
        "colorHex": "#ffffff",
        "specs": [],
        "link": "https://samsung.com.bo/lavadoras/WA80H4200SW"
    },
    {
        "sku": "WD12T704DBX/ZS",
        "name": "Lavadora Secadora 12.5Kg/7Kg con IA",
        "description": "Lavaseca 2 en 1, EcoBubble, Air Wash (Desodorizar) y AI Control.",
        "price": 6930,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_LMZcfWrj4VIyn51mxdGR.png",
        "mainCategory": "Lavadoras / Secadoras",
        "category": "Lavadoras / Secadoras",
        "color": "Gray",
        "colorHex": "#808080",
        "specs": [],
        "link": "https://samsung.com.bo/washers-and-dryers/washer-dryer-combo/wd7500t-front-loading-eco-bubble-quickdrive-ai-control-12-5kg-gray-wd12t754dbn-bo"
    },
    {
        "sku": "RT22FARADS8/ZS",
        "name": "Refrigerador Top Freezer 234L c/ All Around Cooling",
        "description": "Sistema All-Around Cooling, Digital Inverter y compresor duradero (234L útil).",
        "price": 4736,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_5COYXBSuT1VHEmLe0tAG.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Plateado",
        "colorHex": "#dbdbdb",
        "specs": [
            "234L"
        ],
        "link": "https://samsung.com.bo/refrigerators/top-mount-freezer/refrigerator-234l-silver-rt22farads8-zs"
    },
    {
        "sku": "RT31CG5420S9ZS",
        "name": "Refrigerador Top Mount Freezer 301L c/ Space Max",
        "description": "Tecnología SpaceMax (paredes finas), All-Around Cooling y 301L efectivos.",
        "price": 6237,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_sljpqH4KTY7JcAitRfzn.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Silver",
        "colorHex": "#c0c0c0",
        "specs": [
            "301L"
        ],
        "link": "https://samsung.com.bo/refrigerators/top-mount-freezer/rt5300c-top-mount-freezer-spacemax-301l-silver-rt31cg5420s9zs"
    },
    {
        "sku": "RT42CG6720B1ZS",
        "name": "Refrigerador Top Mount Freezer 407 L con Space Max",
        "description": "El doble de frescura con mayor capacidad",
        "price": 9298,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_PXyHfSYxJigNBdR6UCtT.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [
            "407L"
        ],
        "link": "https://samsung.com.bo/refrigerators/top-mount-freezer/rt6300c-top-mount-freezer-optimal-fresh-and-space-max-407l-black-rt42cg6720b1zs"
    },
    {
        "sku": "RT38CG6720S9ZS",
        "name": "Refrigerador Top Mount Freezer 407 L con Space Max",
        "description": "El doble de frescura con mayor capacidad",
        "price": 9009,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_vohCPp2fGgDBs64nty19.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Plateado",
        "colorHex": "#dbdbdb",
        "specs": [
            "407L"
        ],
        "link": "https://samsung.com.bo/refrigerators/top-mount-freezer/rt6300c-top-mount-freezer-optimal-fresh-and-space-max-384l-silver-rt38cg6720s9zs"
    },
    {
        "sku": "RS52B3000B4/ZS",
        "name": "Refrigerador Side by Side 490 L con Twist Ice Maker",
        "description": "Diseño minimalista Side by Side, All-Around Cooling y compresor silencioso.",
        "price": 12058,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_6d7ECzRqcX2IgZFSH1Vt.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Black",
        "colorHex": "#000000",
        "specs": [
            "490L"
        ],
        "link": "https://samsung.com.bo/refrigerators/side-by-side/rs3000bm-side-by-side-modern-and-sleek-design-490l-black-rs52b3000b4-zs"
    },
    {
        "sku": "RS52B3000M9/ZS",
        "name": "Refrigerador Side by Side 490 L con Twist Ice Maker",
        "description": "Diseño minimalista Side by Side, All-Around Cooling y compresor silencioso.",
        "price": 11365,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_C81GHQufw5rAhnMT7XUt.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Silver",
        "colorHex": "#d3d3d3",
        "specs": [
            "490L"
        ],
        "link": "https://samsung.com.bo/refrigerators/side-by-side/rs3000bm-side-by-side-modern-and-sleek-design-490l-black-rs52b3000b4-zs"
    },
    {
        "sku": "RT31CG5540S9ZS",
        "name": "Refrigerador Top Mount Freezer 298 L con Space Max",
        "description": "Almacena más alimentos en un interior espacioso con 20 litros más de capacidad",
        "price": 6699,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_qdOpYe8xzfGi6bklj9RJ.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Silver",
        "colorHex": "#d3d3d3",
        "specs": [
            "298L"
        ],
        "link": "https://samsung.com.bo/refrigerators/top-mount-freezer/rt5300c-top-mount-freezer-spacemax-298l-silver-rt31cg5540s9zs"
    },
    {
        "sku": "RF44A5202B1/ZS",
        "name": "French Door de 425 L con Twin Cooling Plus",
        "description": "Puerta Francesa (Twin Cooling), dispensador de agua externo y caja de vegetales.",
        "price": 15246,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_xgmOh0RCkMKVTP5WieGE.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [
            "425L"
        ],
        "link": "https://samsung.com.bo/refrigerators/french-door/rf5000a-425l-black-rf44a5202b1-zs"
    },
    {
        "sku": "RT53K6541SL/ZS",
        "name": "Refrigerador Twin Cooling Plus de 526 L / 19 Pies cúbicos",
        "description": "Mantén la frescura de tus alimentos por el doble de tiempo",
        "price": 10973,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_ZeLXNjyAPOFGD8znriCB.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Silver",
        "colorHex": "#d3d3d3",
        "specs": [
            "526L"
        ],
        "link": "https://samsung.com.bo/refrigeradores/RT53K6541SL"
    },
    {
        "sku": "RT38K50AJS8/ZS",
        "name": "Top Mount de 385L con No Frost",
        "description": "All-around Cooling",
        "price": 7762,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_y1Ew2vYxhRkjQXpbmz6T.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Plateado",
        "colorHex": "#dbdbdb",
        "specs": [
            "385L"
        ],
        "link": "https://samsung.com.bo/refrigerators/top-mount-freezer/385l-elegant-inox-rt38k50ajs8-zs"
    },
    {
        "sku": "RT53K6541BS/ZS",
        "name": "Refrigerador Twin Cooling Plus de 526 L / 19 Pies cúbicos",
        "description": "Edición Black Inox, Twin Cooling, Smart Conversion y Power Cool/Freeze.",
        "price": 11296,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_EZwrpQvh7dGJfLz8O4SD.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [
            "526L"
        ],
        "link": "https://samsung.com.bo/refrigeradores/RT53K6541BS"
    },
    {
        "sku": "RT38CG6720B1ZS",
        "name": "Refrigerador Top Mount Freezer 384 L c/ Space Max y WiFi",
        "description": "Bespoke Design (Panel personalizable), WiFi SmartThings y SpaceMax.",
        "price": 9240,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_zJbv7fYwk1ruh9PVIHaE.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [
            "384L"
        ],
        "link": "https://shop.samsung.com.bo/refrigerators/top-mount-freezer/rt6300c-top-mount-freezer-optimal-fresh-and-space-max-384l-black-rt38cg6720b1zs"
    },
    {
        "sku": "RT38CG6720S9ZS",
        "name": "Refrigerador Top Mount Freezer 384 L c/ Space Max y WiFi",
        "description": "Bespoke Design (Panel personalizable), WiFi SmartThings y SpaceMax.",
        "price": 9009,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_vohCPp2fGgDBs64nty19.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Plateado",
        "colorHex": "#dbdbdb",
        "specs": [
            "384L"
        ],
        "link": "https://samsung.com.bo/refrigerators/top-mount-freezer/rt6300c-top-mount-freezer-optimal-fresh-and-space-max-384l-black-rt38cg6720b1zs"
    },
    {
        "sku": "RS65R5691M9/ZS",
        "name": "Refrigerador Side by Side 602L c/ 3-Door Flex",
        "description": "Tecnología SpaceMax (602L), 3 puertas con FlexZone y Metal Cooling.",
        "price": 17903,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_xDYXudpNP4qvCsWoOZaQ.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Plateado",
        "colorHex": "#dbdbdb",
        "specs": [
            "602L"
        ],
        "link": "https://samsung.com.bo/refrigerators/side-by-side/rs5000rc-spacemax-602l-black-rs65r5691b4-zs"
    },
    {
        "sku": "RS65R5691B4/ZS",
        "name": "Refrigerador Side by Side 602L c/ 3-Door Flex",
        "description": "Tecnología SpaceMax (602L), 3 puertas con FlexZone y Metal Cooling.",
        "price": 19173,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_4JuPHt1WvOwDnmYhZ6rA.png",
        "mainCategory": "Refrigeradores",
        "category": "Refrigeradores",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [
            "602L"
        ],
        "link": "https://samsung.com.bo/refrigerators/side-by-side/rs5000rc-spacemax-602l-black-rs65r5691b4-zs"
    },
    {
        "sku": "VC18M3110VB/BO",
        "name": "Aspiradora sin Bolsa 1800W c/ Turbina Anti Enredos",
        "description": "Turbina Anti-Tangle (No se atasca con pelos), depósito Easy Dustbin y 1800W.",
        "price": 1247,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_xjtC0g9Z2bEXqADP3HNy.png",
        "mainCategory": "Aspiradoras",
        "category": "Aspiradoras",
        "color": "Azul Cosmo",
        "colorHex": "#1c0d82",
        "specs": [],
        "link": "https://samsung.com.bo/vacuum-cleaners/canister/canister-vc3100m"
    },
    {
        "sku": "VCC4190V3E/XBO",
        "name": "Aspiradora con Bolsa 2000W c/ Función Soplador",
        "description": "Potente 2000W, función de soplado de polvo y filtro de alérgenos.",
        "price": 901,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_hx8bfBduoXV1MyCcHAlZ.png",
        "mainCategory": "Aspiradoras",
        "category": "Aspiradoras",
        "color": "Vino Rubí",
        "colorHex": "#653038",
        "specs": [],
        "link": "https://samsung.com.bo/vacuum-cleaners/canister/vcc4190v3exbo"
    },
    {
        "sku": "VS15A60A1R5/ZS",
        "name": "Aspiradora Stick Jet 60 con 150 W de Poder de Succión",
        "description": "Rendimiento de limpieza más avanzado",
        "price": 3049,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_a3s8g25FhCHW6MLPTDRy.png",
        "mainCategory": "Aspiradoras",
        "category": "Aspiradoras",
        "color": "Silver",
        "colorHex": "#d3d3d3",
        "specs": [],
        "link": "https://samsung.com.bo/vacuum-cleaners/stick/vs9000rl-stick-more-advance-cleaning-performance-digital-inverter-motor-jet-cyclone-silver-vs15a60a1r5-zs"
    },
    {
        "sku": "VCC4580V3K/XBO",
        "name": "Aspiradora con Contenedor , 2000 W",
        "description": "Twin Chamber System™",
        "price": 1040,
        "salePrice": 0,
        "image": "https://samsung-bolivia.s3.amazonaws.com/product-family-item-image-image/square/product-family-item-image-image_0wEIO2gtvuZmicUy9WNT.png",
        "mainCategory": "Aspiradoras",
        "category": "Aspiradoras",
        "color": "Negro",
        "colorHex": "#000000",
        "specs": [],
        "link": "https://samsung.com.bo/vacuum-cleaners/canister/canister-vcc4580v3k"
    }
];
